/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formreservasihotel;

import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author WINDOWS 10
 */
public class FormReservasiHotel extends javax.swing.JFrame {

    /**
     * Creates new form FormReservasiHotel
     */
    public FormReservasiHotel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jnsKmr = new javax.swing.ButtonGroup();
        Tab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        noTran = new javax.swing.JLabel();
        tglRes = new javax.swing.JLabel();
        noHP = new javax.swing.JLabel();
        noKTP = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        checkIn = new javax.swing.JLabel();
        checkOut = new javax.swing.JLabel();
        depo = new javax.swing.JLabel();
        biaTam = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        txNoTran = new javax.swing.JTextField();
        txTglRes = new javax.swing.JTextField();
        txNoHp = new javax.swing.JTextField();
        txNoKtp = new javax.swing.JTextField();
        txNama = new javax.swing.JTextField();
        txCheckIn = new javax.swing.JTextField();
        txCheckOut = new javax.swing.JTextField();
        txDepo = new javax.swing.JTextField();
        txBiaTam = new javax.swing.JTextField();
        txTotal = new javax.swing.JTextField();
        check = new javax.swing.JButton();
        preview = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tArea = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        noKa = new javax.swing.JLabel();
        tiKa = new javax.swing.JLabel();
        jeKa = new javax.swing.JLabel();
        tarif = new javax.swing.JLabel();
        txNoKa = new javax.swing.JTextField();
        txTiKa = new javax.swing.JTextField();
        txTarif = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        rdSingle = new javax.swing.JRadioButton();
        rdDouble = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPesan = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(500, 600));
        getContentPane().setLayout(null);

        noTran.setText("No. Transaksi");

        tglRes.setText("Tgl Reservasi");

        noHP.setText("No.HP");

        noKTP.setText("No.KTP");

        nama.setText("Nama");

        checkIn.setText("Check In");

        checkOut.setText("Check Out");

        depo.setText("Deposit");

        biaTam.setText("Biaya Tambahan");

        total.setText("Total");

        txCheckIn.setText("dd/mm/yyyy");

        txCheckOut.setText("dd/mm/yyyy");

        txDepo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txDepoActionPerformed(evt);
            }
        });

        check.setText("Check");
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });

        preview.setText("Preview");
        preview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(checkIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(depo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(noKTP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(noHP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tglRes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(noTran, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                    .addComponent(biaTam))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txBiaTam)
                    .addComponent(txTglRes, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txNoHp, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txNoKtp, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txNama, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txCheckIn, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txCheckOut, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txDepo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txTotal)
                    .addComponent(txNoTran, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(37, 37, 37))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(check, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(preview, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noTran, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txNoTran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tglRes, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txTglRes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noHP, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txNoHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noKTP, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txNoKtp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkIn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkOut, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txDepo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(biaTam, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txBiaTam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(check)
                    .addComponent(preview))
                .addGap(45, 45, 45))
        );

        Tab.addTab("Pesan", jPanel1);

        tArea.setColumns(20);
        tArea.setRows(5);
        jScrollPane1.setViewportView(tArea);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                .addContainerGap())
        );

        Tab.addTab("Preview", jPanel2);

        getContentPane().add(Tab);
        Tab.setBounds(20, 40, 380, 450);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        noKa.setText("No. Kamar");

        tiKa.setText("Tipe Kamar");

        jeKa.setText("Jenis Kamar");

        tarif.setText("Tarif");

        txNoKa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txNoKaKeyTyped(evt);
            }
        });

        txTarif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txTarifActionPerformed(evt);
            }
        });

        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        jnsKmr.add(rdSingle);
        rdSingle.setText("Single");

        jnsKmr.add(rdDouble);
        rdDouble.setText("Double");

        tblPesan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No Kamar", "Tipe", "Jenis", "Tarif"
            }
        ));
        jScrollPane2.setViewportView(tblPesan);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tiKa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tarif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jeKa, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(noKa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txTarif)
                    .addComponent(txNoKa)
                    .addComponent(txTiKa)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(rdSingle, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rdDouble, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noKa, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txNoKa, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tiKa, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txTiKa, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jeKa, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdSingle, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rdDouble)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tarif, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txTarif, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(add)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(420, 60, 320, 430);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel11.setText("Reservasi Hotel");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(290, 10, 280, 40);

        jButton1.setText("Quit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(90, 510, 620, 30);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txDepoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txDepoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txDepoActionPerformed

    private void txTarifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTarifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTarifActionPerformed

    private void txNoKaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txNoKaKeyTyped

        angka(evt);
        //---3 adalah jumlah karakter yang saya inginkan
        if (txNoKa.getText().length() > 2) {
            //your command, for examples:
            JOptionPane.showMessageDialog(null, "Maaf Angka Terlalu Panjang!!!");
            evt.consume(); //---karakter tidak akan di Input
        }
    }//GEN-LAST:event_txNoKaKeyTyped

    private void previewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previewActionPerformed
        Tab.setSelectedIndex(1);
        tArea.setText("");
        tArea.append("====Aplikasi Hotel====");
        tArea.append("\n");
        tArea.append("Pemesan : " + txNama.getText());
        tArea.append("\n");
        tArea.append("Lama Hari : " + lama2);
        tArea.append("\n");
        tArea.append("=========================\n");
        tArea.append("N.Kamar \tTipe\tJenis\tTarif\n");
        tArea.append("=========================\n");
        for (int i = 0; i < model.getRowCount(); i++) {
            String a = (String) model.getValueAt(i, 0) + "\t"
                    + model.getValueAt(i, 1) + "\t" + model.getValueAt(i, 2)
                    + "\t" + model.getValueAt(i, 3);
            tArea.append(a);
            tArea.append("\n");
        }
        tArea.append("==========================\n");
        tArea.append("Total : " + tot);
        tArea.append("\n");
    }//GEN-LAST:event_previewActionPerformed

    private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed
        // TODO add your handling code here:
        cekV();
        biayaTam = Double.parseDouble(txBiaTam.getText());
        tar = Integer.parseInt(txTarif.getText());
        try {
            SimpleDateFormat date = new SimpleDateFormat("dd/MM/yyyy");
            String cIn = txCheckIn.getText();
            String cOut = txCheckOut.getText();
            Date tglCin = (Date) date.parse(cIn);
            Date tglCout = (Date) date.parse(cOut);
            lama = Math.abs(tglCout.getTime() - tglCin.getTime());
            System.out.println(lama);
            lama2 = TimeUnit.MILLISECONDS.toDays(lama);
            System.out.println(lama2);
            for (int i = 0; i < model.getRowCount(); i++) {
                String a = String.valueOf(model.getValueAt(i, 3));
                totTarif += Double.parseDouble(a);
            }
            deposit = Double.parseDouble(txDepo.getText());
            tot = deposit - (lama2 * totTarif) - biayaTam;
        } catch (NumberFormatException e) {
            System.err.println("kesalahan "+e);
        } catch (ParseException ex) {
            Logger.getLogger(FormReservasiHotel.class.getName()).log(Level.SEVERE, null, ex);
        }
        txTotal.setText(Double.toString(tot));
    }//GEN-LAST:event_checkActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        cekV();
        String jKmar, jenis;
        if (rdSingle.isSelected()) {
            jKmar = "500000";
            jenis = "SINGLE";
        } else {
            jKmar = "700000";
            jenis = "DOUBLE";
        }
        if (txNoKa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Jangan Kosong !!");
        } else {
            //addrow
            model = (DefaultTableModel) tblPesan.getModel();
            
            txTarif.setText(jKmar);
            model.addRow(new Object[]{
                txNoKa.getText(), txTiKa.getText(), jenis, jKmar});
        }
    }//GEN-LAST:event_addActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    // atribut
    double deposit, biayaTam, tot, totTarif, tar;
    long lama, lama2;
    DefaultTableModel model = new DefaultTableModel();

    void angka(java.awt.event.KeyEvent evt) {
        char kar = evt.getKeyChar();
        if (!((kar >= '0') && kar <= '9')
                || (kar == KeyEvent.VK_BACK_SPACE)
                || (kar == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }
    }

    void cekV() {
        if (txNoTran.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Field tidak boleh kosong");
        }
        if (txNoKa.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Field tidak boleh kosong");
        }
        String format = "dd/mm/yyyy";
        SimpleDateFormat sdf = new SimpleDateFormat(format);
        sdf.setLenient(false);
        try {
            Date date = sdf.parse(txCheckIn.getText());
            if (!sdf.format(date).equals(txCheckIn.getText())) {
                throw new ParseException(txCheckIn.getText() + " is not valid format for " + format, 0);
            }
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(rootPane, "salah format tanggal");
        }
        if (txCheckIn.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "salah format tanggal");
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormReservasiHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormReservasiHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormReservasiHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormReservasiHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormReservasiHotel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Tab;
    private javax.swing.JButton add;
    private javax.swing.JLabel biaTam;
    private javax.swing.JButton check;
    private javax.swing.JLabel checkIn;
    private javax.swing.JLabel checkOut;
    private javax.swing.JLabel depo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jeKa;
    private javax.swing.ButtonGroup jnsKmr;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel noHP;
    private javax.swing.JLabel noKTP;
    private javax.swing.JLabel noKa;
    private javax.swing.JLabel noTran;
    private javax.swing.JButton preview;
    private javax.swing.JRadioButton rdDouble;
    private javax.swing.JRadioButton rdSingle;
    private javax.swing.JTextArea tArea;
    private javax.swing.JLabel tarif;
    private javax.swing.JTable tblPesan;
    private javax.swing.JLabel tglRes;
    private javax.swing.JLabel tiKa;
    private javax.swing.JLabel total;
    private javax.swing.JTextField txBiaTam;
    private javax.swing.JTextField txCheckIn;
    private javax.swing.JTextField txCheckOut;
    private javax.swing.JTextField txDepo;
    private javax.swing.JTextField txNama;
    private javax.swing.JTextField txNoHp;
    private javax.swing.JTextField txNoKa;
    private javax.swing.JTextField txNoKtp;
    private javax.swing.JTextField txNoTran;
    private javax.swing.JTextField txTarif;
    private javax.swing.JTextField txTglRes;
    private javax.swing.JTextField txTiKa;
    private javax.swing.JTextField txTotal;
    // End of variables declaration//GEN-END:variables
}
